#!/bin/sh
# The warriors and the manual the binary carries, as C: plain byte arrays
# (od), so no compiler needs #embed.
# usage: library.sh MANUAL WARRIOR.red... > build/library.c
set -eu
manual=${1:?usage: library.sh MANUAL WARRIOR.red...}
shift
bytes() {
	od -An -v -tu1 "$1" | awk '{for (i = 1; i <= NF; i++) printf "%s,", $i; print ""}'
}
printf '/* generated by tools/library.sh: do not edit */\n#include "library.h"\n\n'
i=0
for f in "$@"; do
	printf 'static const uint8_t w%d[] = {\n' "$i"
	bytes "$f"
	printf '};\n'
	i=$((i + 1))
done
printf '\nconst cw_file cw_library[] = {\n'
i=0
for f in "$@"; do
	printf '    {"%s", w%d, sizeof w%d},\n' "$(basename "$f")" "$i" "$i"
	i=$((i + 1))
done
printf '};\n\nconst size_t cw_library_n = %d;\n\n' "$i"
printf 'const uint8_t cw_manual[] = {\n'
bytes "$manual"
printf '};\n\nconst size_t cw_manual_len = sizeof cw_manual;\n'
